### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by minad** [JuliaMath/openlibm#193]
In the light of https://github.com/JuliaLang/julia/issues/18102 and https://github.com/JuliaLang/julia/issues/26434, what is the status of this project not within the context of Julia? Is it effectively unmaintained? Are there other libm alternatives, which can be recommended? In https://github.com/JuliaLang/julia/issues/18102 msun was mentioned, but then I wonder what patches of openlibm are lost?

ping @ViralBShah

**Comment by ViralBShah** [comment]
For now, this will continue to ship in Julia and we are some ways away from removing the dependency in Julia.

Otherwise it is generally a complete package. Openlibm had received quite a few patches at this point and diverged from msun many years ago. Someone could look at msun and port major fixes if any.

I imagine there are enough users of this library at this point that it will keep being maintained.

Musl libm may be another option.

**Comment by minad** [comment]
@ViralBShah Thank you! Sounds good. I think I will continue to use openlibm for now. Musl also has quite high quality, but extacting the libm from it is probably a bit of work. It is a major advantage of openlibm, that it can be used for freestanding builds. I guess we can close this issue?
