### ISSUE TITLE
Let's tag 0.7.0

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/openlibm#200]
Should we tag the current master as 0.6.1?

**Comment by ararslan** [comment]
For reference, the commits from 0.6.0 to current master: https://github.com/JuliaMath/openlibm/compare/v0.6.0...master

**Comment by ginggs** [comment]
I ran test builds of current HEAD on Ubuntu 20.04.  No problems on amd64, arm64 and ppc64el.

Two symbols were dropped on armhf (32-bit ARM):
fdiml@Base and scalblnl@Base
Is that expected?
https://launchpadlibrarian.net/454770434/buildlog_ubuntu-focal-armhf.openlibm_0.6.1-0ubuntu1~ppa1_BUILDING.txt.gz

There were several symbols added and removed on s390x.
https://launchpadlibrarian.net/454770344/buildlog_ubuntu-focal-s390x.openlibm_0.6.1-0ubuntu1~ppa1_BUILDING.txt.gz

Should the SONAME be bumped because of these?

**Comment by ViralBShah** [comment]
We should look into arm. Not sure what's happening on s390 - but someone who is interested in that architecture should take a look - perhaps @sharkcz

**Comment by sharkcz** [comment]
s390x is a new port for 0.6.1, so there shouldn't be any compatibility issues

**Comment by ginggs** [comment]
My mistake!  Somehow I used the debian packaging files from 0.6.0+dfsg-1, instead of 0.6.0+dfsg-2 (which cherry-picked the s390x port).

There are still two dropped symbols on 32-bit arm:
https://launchpad.net/~ginggs/+archive/ubuntu/testing/+build/18226111/+files/buildlog_ubuntu-focal-armhf.openlibm_0.6.1-0ubuntu1~ppa2_BUILDING.txt.gz

...but there are  no problems on s390x.

**Comment by ViralBShah** [comment]
Those are dropped on arm because we are disabling OPENLIBM_LONG_DOUBLE on arm, which doesn't build. Not sure if it built in the past.

**Comment by ViralBShah** [comment]
I think we should tag as v0.7.0 as a result of the above. Thanks @ginggs.

**Comment by ViralBShah** [comment]
Also noting the SONAME bump to 3.0 in 5efed306d509905714e3c43fc3a43fb26f3df743
