### ISSUE TITLE
olm_ prefixes for openlibm functions

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/openlibm#5]
@vtjnash, @loladiro, Do you think we should have olm_ prefixes for openlibm functions, so that they don't clash with the system libm?

This could be done through a macro, which allows use of libm names, or with a prefix, depending on what the user wants.

**Comment by EdSchouten** [comment]
The code in https://github.com/JuliaLang/openlibm/pull/77 would actually make this rather easy to support. All source files will include <openlibm.h> and obtain the prototypes through there. We could simply put a macro in that header and use that in all of the sources:

#define OLM_F(name) olm_##

float OLM_F(cosf)(float x) {
  ...
}

It would also make the code slightly cleaner, because we could get rid of the __ieee754_*() garbage at the same time.

**Comment by ViralBShah** [comment]
@EdSchouten This is too much to ask - but if you have tried this, could you please submit a PR? It will be so much cleaner to use code with the prefixes, when one needs to be absolutely sure about calling the right versions.

**Comment by ViralBShah** [comment]
I wondered why the __ieee754_* stuff was there.

**Comment by ViralBShah** [comment]
I am thinking of doing the name mangling, and then linking to the system `-lm` and also simultaneously having the option of using host's fenv.h. That way, we don't have to manage the messy floating point exception stuff, where we are better off using the system provided one.
